---
_extends: .github

repository:
  name: website
  description: The TokTok website
  topics: toktok, tox
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "code-review/reviewable"
          - "docker"
          # Netlify tests:
          - "Header rules - toktok"
          - "Pages changed - toktok"
          - "Redirect rules - toktok"
          - "Mixed content - toktok"
          - "netlify/toktok/deploy-preview"
