name: ci

on:
  pull_request:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          tags: toxchat/toktok.github.io:latest
          outputs: type=docker
      - name: Extract toktok-site directory from docker image
        run: docker run --rm --entrypoint tar toxchat/toktok.github.io:latest -C /home/builder/build -c toktok-site | tar -x
      - name: Upload toktok-site to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toktok-site
          path: toktok-site
          if-no-files-found: error
