name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          tags: toxchat/toktok.github.io:latest
