name: pages

on:
  push:
    branches: [master]

# Cancel old builds when pushing new commits.
concurrency:
  group: pages-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          tags: toxchat/toktok.github.io:latest
          outputs: type=docker
      - name: Extract toktok-site directory from docker image
        run: docker run --rm --entrypoint tar toxchat/toktok.github.io:latest -C /home/builder/build -c toktok-site | tar -x
      - name: Set-up Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: toktok-site
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
